#!/bin/bash

file="/sys/class/backlight/intel_backlight/brightness"
current=$(cat $file)
max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
min=128

polybar-signal() {
    polybar-msg hook backlight 1
}

increase() {
    current=$(( 2 * $current ))
    if [ $current -le $max ]; then
        echo $current > $file
    else
        echo $max > $file
    fi
    polybar-signal
}

decrease() {
    if [ $current -eq $max ]; then
        current=$(( ($current / 2) + 1 ))
    else
        current=$(( $current / 2 ))
    fi
    if [ $current -ge $min ]; then
        echo $current > $file
    else
        echo $min > $file
    fi
    polybar-signal
}

if [ $# -ge 1 ]; then
    case "$1" in
        increase) ;&
        inc)
            increase;;
        decrease) ;&
        dec)
            decrease;;
        *)
            echo "Unknown option $1"
            echo "backlight  [increase|decrease]"
    esac
fi

level=$(echo "l($current + 1)/l(2)" | bc -l | awk -F. '{print $1}')
percent=$(( $(( $level - 6 )) * 10 ))
echo $percent%


