#!/bin/bash

# Script to control the touch gestures to open and close top bar

SCRIPT_DIR=$(dirname $(realpath $0))
source $SCRIPT_DIR/dimensions

mouse_y() {
    eval $(xdotool getmouselocation -shell)
    echo $Y
}

until_release() {
    # Use xinput --list to find the index of touchscreen device
    xinput test 8 | (sed '/release/ q' && killall xinput)
}

position_panel() {
    win_pos=$1
    cur_height=$((win_pos + HEIGHT_FULL))
    if [ $win_pos -le $Y_FULL -a $win_pos -ge $Y_CLOSED ]; then
        $SCRIPT_DIR/polybar set_height $win_pos
    fi

    if [ $cur_height -le $HEIGHT_MED ]; then
        $SCRIPT_DIR/launcher set_height $((cur_height - HEIGHT_MED + LAUNCHER_Y))
    fi
    if [ $cur_height -ge $HEIGHT_FULL_THRESH ]; then
        $SCRIPT_DIR/launcher set_height $((LAUNCHER_Y + HEIGHT_FULL_THRESH - cur_height))
    fi

    if [ $win_pos -le $Y_FULL -a $win_pos -ge $Y_MED ]; then
        local panel_height=$(( 2*win_pos + 50  ))
        $SCRIPT_DIR/info_panel set_height $panel_height
    fi
}



animate() {
    local win_start=$($SCRIPT_DIR/polybar get_height)
    local win_prev_pos=$win_start
    local cursor_start=$(mouse_y)
    $SCRIPT_DIR/launcher show
    while true; do
        cursor_pos=$(mouse_y)
        win_pos=$((cursor_pos - cursor_start + win_start))
        position_panel $win_pos

        local momentum=$((win_pos - win_prev_pos))
        echo $momentum > /tmp/tablet_mode_animate_bar_momentum
        win_prev_pos=$win_pos
    done
}

snap_to() {
    local start_pos=$2
    case "$1" in
        closed)
            for win_pos in `seq $start_pos -40 $Y_CLOSED`; do
                position_panel $win_pos
            done
            position_panel $Y_CLOSED
            ;;
        med)
            if [ $start_pos -ge $Y_MED ]; then
                for win_pos in `seq $start_pos -40 $Y_MED`; do
                    position_panel $win_pos
                done
            else
                for win_pos in `seq $start_pos 40 $Y_MED`; do
                    position_panel $win_pos
                done
            fi
            position_panel $Y_MED
            ;;
        full)
            for win_pos in `seq $start_pos 40 $Y_FULL`; do
                position_panel $win_pos
            done
            position_panel $Y_FULL
            ;;
    esac
}

animate &
ANIM_PID=$!
until_release
kill $ANIM_PID

# Snap to the closest bar state
win_pos=$($SCRIPT_DIR/polybar get_height)
momentum=$(cat /tmp/tablet_mode_animate_bar_momentum)
cur_height=$((win_pos + HEIGHT_FULL))

if [ $cur_height -le $HEIGHT_MED ]; then
    if [ $((cur_height+momentum)) -le $HEIGHT_MED_THRESH ]; then
        snap_to closed $win_pos
    else
        snap_to med $win_pos
    fi
else
    if [ $((cur_height+momentum)) -le $HEIGHT_FULL_THRESH ]; then
        snap_to med $win_pos
    else
        snap_to full $win_pos
    fi
fi
