#!/bin/bash

set_fan() {
    local fan_perc=$1
    echo "Target fan speed: $fan_perc%"
    nvidia-settings -a "[gpu:0]/GPUFanControlState=1" \
                    -a "[fan:0]/GPUTargetFanSpeed=$1"  &> /dev/null
}

while true; do 
    sleep 5
    temp=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)
    echo -ne "Temperature: $temp C\t"
    # Cubic function that ramps up to 100% at 80 C and idles around 20%
    target=$((9*temp*temp*temp/51200 + 10))
    set_fan $target
done

