#!/bin/bash

# Wrapper to control polybar for tablet mode

CONF=~/.config/polybar/config-tablet
ID_TOP=/tmp/tablet_pid
ID_OPTIONS=/tmp/tablet_options_pid
ID_LAUNCHER=/tmp/tablet_launcher_pid

launch() {
    # Hide landscape bar
    ~/.i3/scripts/polybar_wrapper hide
    polybar -c $CONF top &
    echo $! > $ID_TOP
    polybar -c $CONF applauncher &
    echo $! > $ID_LAUNCHER
    for i in 1 2 3; do
        polybar -c $CONF option_menu$i &
        echo $! > ${ID_OPTIONS}_$i
    done

    sleep 0.5
    ~/.i3/scripts/polybar_modules/tablet_launcher open
    ~/.i3/scripts/polybar_modules/tablet_launcher close
}

close() {
    kill $(cat $ID_TOP)
    kill $(cat $ID_LAUNCHER)
    for i in 1 2 3; do
        kill $(cat ${ID_OPTIONS}_$i)
    done
    ~/.i3/scripts/polybar_wrapper show
}

show_rofi() {
    ~/.i3/scripts/polybar_modules/tablet_options close
    onscreen_keyboard show
    rofi -show run -font "Dejav Vu Sans Mono 24" -width 600 -padding 32
    onscreen_keyboard hide
}

case "$1" in
    launch) launch;;
    close)  close;;
    rofi)   show_rofi;;
esac
