#!/usr/bin/env bash

# Convenience wrapper for launching different rofi modes w/ associated themes

case "$1" in
    run)
        rofi -modi run -show run -theme run \
             -display-run "Run command";;
    applications)
        rofi -modi drun -show drun -theme drun \
             -display-drun "Launch application" \
             -drun-categories Curated;;
    games)
        rofi -modi drun -show drun -theme games \
             -display-drun "Launch game" \
             -drun-categories SteamLibrary;;
    window)
        rofi -modi window -show window -theme window \
             -display-window "Search open windows";;
    options)
        rofi_option_menu;;
esac
