#!/bin/bash

DIR=$(dirname $(realpath $0))

      LOCK="\tLock"
    ROTATE="\tRotate"
    LOGOUT="\tLogout"
  CHROMEOS="\tChromeOS"
SCREENSHOT="\tScreenshot"

list_icons() {
    echo -e "$LOCK"
    echo -e "$ROTATE"
    echo -e "$LOGOUT"
    echo -e "$CHROMEOS"
    echo -e "$SCREENSHOT"
}

handle_option() {
    local opt=$(echo "$1" | awk '{print $2}')
    case "$opt" in
        "Lock")
            $DIR/betterlockscreen -l blur
            ;;
        "Rotate")
            ~/bin/tablet_mode
            ;;
        "Logout")
            if $($DIR/rofi_confirm "$LOGOUT"); then
                i3-msg exit
            fi
            ;;
        "ChromeOS")
            # Switch crouton hotkey
            xdotool key control+alt+shift+F1 
            ;;
        "Screenshot")
            scrot -e 'feh $f -x' --delay 1 &
            ;;
        *)
            echo "Error"
    esac
}

SELECTION="$(list_icons | rofi -dmenu -theme options_menu)"
handle_option "$SELECTION"
