#!/usr/bin/env bash

PRIMARY=$(xrdb -query | awk '/^*primary:/ {print $2}')
BG_ALT="#434C5E"
TEXT="#D8DEE9"
CYAN="#88C0D0"
BLUE="#5E81AC"
RED="#BF616A"
ORANGE="#D08770"
YELLOW="#EBCB8B"
GREEN="#A3BE8C"
PURPLE="#B48EAD"
    
text_height=30
text_offset=4

glyph() {
    echo -n "\${font Font Awesome 5 Free:style=Solid}$1\${font}"
}

conky_graph() {
    local OPTIND=1
    local arg graph x y width height scale text color
    color=$PRIMARY

    while getopts 'g:x:y:w:h:s:t:c:' arg
    do
        case ${arg} in
            g) graph=${OPTARG};;
            x) x=${OPTARG};;
            y) y=${OPTARG};;
            w) width=${OPTARG};;
            h) height=${OPTARG};;
            s) scale=${OPTARG};;
            t) text=${OPTARG};;
            c) color=${OPTARG};;
            *) return 1 # illegal option
        esac
    done
   
    echo -n "\${voffset $((y-10))}"
    echo -n "\${goto $x}"
    echo -n "\${color $color}" 
    echo -n "\${$graph $height,$width $color $color $scale 0}"
    echo -n "\${color $TEXT}"
    echo -n "\${goto $((x+12))}"
    echo -n "\${voffset 16}"
    echo -n "$text"
    echo -n "\${voffset -16}"
    echo -n "\${voffset -$((y-10))}"
}

conky_bar() {
    local OPTIND=1
    local arg bar x y width height text color
    color=$PRIMARY

    while getopts 'b:x:y:w:h:c:' arg
    do
        case ${arg} in
            b) bar=${OPTARG};;
            x) x=${OPTARG};;
            y) y=${OPTARG};;
            w) width=${OPTARG};;
            h) height=${OPTARG};;
            c) color=${OPTARG};;
            *) return 1 # illegal option
        esac
    done

    echo -n "\${voffset $y}"
    echo -n "\${goto $x}"
    echo -n "\${color $color}"
    echo -n "\${$bar $height,$width}"
    echo -n "\${color $TEXT}"
    echo -n "\${voffset -$y}"
}

conky_frame() {
    local OPTIND=1
    local arg x y width height color
    color=$PRIMARY

    while getopts 'x:y:w:h:c:' arg
    do
        case ${arg} in
            x) x=${OPTARG};;
            y) y=${OPTARG};;
            w) width=${OPTARG};;
            h) height=${OPTARG};;
            c) color=${OPTARG};;
            *) return 1 # illegal option
        esac
    done
   
    echo -n "\${goto $x}"
    echo -n "\${voffset $((y-10))}"
    echo -n "\${color $color}" 
    echo -n "\${execigraph 1000 \"echo 0\" $height,$width}"
    echo -n "\${voffset -$((y-10))}"
}

conky_element() {
    local OPTIND=1
    local arg element x y width color align
    color=$TEXT
    align=0

    while getopts 'e:x:y:w::c:a' arg
    do
        case ${arg} in
            e) element="${OPTARG}";;
            x) x=${OPTARG};;
            y) y=${OPTARG};;
            w) width=${OPTARG};;
            c) color=${OPTARG};;
            a) align=1;;
            *) return 1 # illegal option
        esac
    done
   
    echo -n "\${voffset $y}"
    if [[ $align -eq 1 ]]; then
        nchar=$(expr length "$element")
        text_len=$((nchar * 6))
        offset=$(( (width - text_len)/2 ))
        echo -n "\${goto $((x + offset))}"
    else
        echo -n "\${goto $x}"
    fi
    echo -n "\${color $color}" 
    echo -n "$element"
    echo -n "\${voffset -$y}"
}

conky_header() {
    echo "conky.text = [["
}

conky_footer() {
    echo "]]"
}
